spring:
  application:
    name: leaseflow
  datasource:
    url: jdbc:h2:mem:leaseflow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

server:
  port: 8080
